@startuml classes
class Catalog {
  + add(item : Item)
  + search(word : String) : Item[]
}
class Item {
  -uuid : Number
  -description : String
}
class ContainerList {
  + add(container : Container)
  + getAllLocations() : String[]
  + getAllDrawers() : String[]
  + search(word : String) : Container[]
}
class Container {
  -uuid : Number
  -location : String
  -drawer : String
  -label : String
}
class Inventory {
  + modify(item : Item, container : Container, quantity : Number)
  + findByItem(item : Item) : InventoryLine[]
  + findByContainer(container : Container) : InventoryLine[]
}
class InventoryLine {
  -quantity
}

Catalog *--> Item
ContainerList *--> Container
Inventory *--> InventoryLine
InventoryLine --> Container
InventoryLine --> Item
@enduml
