@startuml classes
class Catalog
class Item {
  -description
}
class Container {
  -location
  -drawer
  -id
}
class ItemInventory {
  -quantity
}
Catalog *-- Item
Container o-- ItemInventory
ItemInventory -- Item
@enduml
