@startdot navigation
digraph g {
  graph [rankdir=LR,
         ranksep=1];
  node [shape = note];

  navigation [label="Navigation", shape=rectangle];
  item_form [label="Formulaire article"];
  container_form [label="Formulaire conteneur"];
  item_list [label="Liste articles"];
  container_list [label="Liste conteneurs"];
  inventory_details [label="Détails inventaire"];

  navigation -> item_list;
  item_list -> item_form;
  navigation -> container_list;
  container_list -> container_form;
  item_list -> inventory_details;
  container_list -> inventory_details;
}
@enddot
