@startdot navigation
digraph g {
  graph [rankdir=LR,
         ranksep=1];
  node [shape = note];

  home [label="Page d'accueil"];
  item_form [label="Formulaire article"];
  container_form [label="Formulaire conteneur"];
  item_list [label="Liste articles"];
  container_list [label="Liste conteneurs"];
  inventory_details [label="Détails inventaire"];

  home -> item_form;
  home -> container_form;
  home -> item_list;
  home -> container_list;
  item_list -> inventory_details;
  container_list -> inventory_details;
}
@enddot
