@startuml usecases
left to right direction

actor "FabLab manager" as manager

rectangle "fablab-components" {
  (Encoder un nouveau composant) as UC1
  (Enregistrer un conteneur) as UC2
  (Rechercher un composant) as UC3
  (Rechercher un conteneur) as UC4
  (Modifier l'inventaire d'un conteneur) as UC5
}

manager --> UC1
manager --> UC2
manager --> UC3
manager --> UC4
manager --> UC5

@enduml
