@startuml usecases
left to right direction

actor "FabLab manager" as manager

rectangle "fablab-components" {
  (UC1: Encoder un nouvel article) as UC1
  (UC2: Enregistrer un conteneur) as UC2
  (UC3: Rechercher un article) as UC3
  (UC4: Rechercher un conteneur) as UC4
  (UC5: Modifier l'inventaire d'un conteneur) as UC5
  (UC6: Modifier l'inventaire d'un composant) as UC6
}

manager --> UC1
manager --> UC2
manager --> UC3
manager --> UC4
manager --> UC5
manager --> UC6

@enduml
